language: node_js

addons:
  firefox: 56.0

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.7.0
  - export PATH=$HOME/.yarn/bin:$PATH

cache:
  yarn: true

env:
  global:
  # ARGOS
  - secure: Zb/aSoJsPUGroCYC8Abjc090BeszQmdC8UqJgkt5/WLuohfdE/Uj0qECTuyOf4LsS/J8qtkET3dYDstTEnS0u9I7BxFbGWjeqGR/ud/qKkf4c8xxQC8EtkMNIxO+a6SaTZZuUZqbfbzP0VUA6OVcWsyCEyHlvzCxpWlqX4C+FYUowdh+z72DqQPei5C9pqDRjdvMfqDn8YuI6A5oxiym/hDydTfGujpzZ90H8aICBcwp0rKnZRWKwCDjVV53aFIc/yDMt9npmHPuE4ITnedTdth/ZW6aiYTB4UUhMKSJANiBact/wOJGaOm/3GzW359Xlo4A1d20u6s8c2oUoq00kyvQuRrE7R9KrX7z6eP+5dOyNbh9eT98y9yz18uD4Bzf9AvV0yhVa7c1p01uZnl5SSlgErwm5u4MhkQ4gp8kKo7AvluurtlY21ao9iypVeia9ahLBHRjq4Q8gtBhR2DZMzhmYal8S4Zm3jKnOH0h1BFlT0dIhcUNuabufO/zNOZC4lvd+VZweGzZWCXG0TBGgmBaj7Vhz8xS/tofqW4omLEQCq7xufXiVEZEMqkFbh5syDUV1EhpssmmN4tO9Hht1joI3xpqbMgMCXN3JVJeCl/mgxmn/lE2RNSXepc/SIWwipUVyzB/a8ItflPavKYUxy9cZz1xyKLPYGn/FUy7RU4=

  # BUNDLESIZE
  - secure: l0CdetUt1XFFO7W6qdamf5XkMsk/lkFx0NY5hjfhiBgCDOa5HvD7JeUlSwszM6MkbRqU/x4zoh8DomtZ19OAwxVapfo83YeMWyOmrbj7xjmuZeaAqI0KIQTSCpMaWq1NgD4NFWrkRIezzOUsbH65OGgMyUUtz8CBz0oKcf4BNO3o1scqAgwLKDuH0b+KQbCruR4rZlsmIY7jRsOKOJk2FV8mFJscF7vaF0Wg8/pfN4MfCQC8qGiOxqqBImCWo3LdIPZmOXTcr/+yBYzIA3fHudrZw9pYMVAFeifuaOA4wW03IPHpN7ppOa3XMPdy5kbXnVQoCWPfWGTSEuCemw0AtP+9hwQPeZgMnl9Mh+/5sIL9K3almtpRMaiOyNQyNF4ZAqt+QMkaHJF5d2SXBJ0D+irG5sOWICjzK4BR+lPv7kkSnuvN+1+fVRrEqX2GhSqYRgoyJYi/HF38AUy1NDIdcJXVipP7luSSnl1DNrmgTmXE+L+WcXkYdM8N5e2lQNApGeQlTZGYOE+w1AHrW4ISfI/jUGSASVkpuHGQnIFC2gCGqSrnk0VVbMCHHbQdyazhKxn8jSenqf4IOx3bmWawlP51emTeKF9/sb/5k2KLqhcLohu0Nfa4sVKRuneadxiDzXBWl+QrgUSURdsGoMvx7vsUoOye7GDLc+VyFI3oxqA=
