language: node_js
node_js: stable
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
before_install:
- git config --global user.email "algobot@users.noreply.github.com"
- git config --global user.name "algobot"
- rvm install 2.3.1
- rvm use 2.3.1
script: "./scripts/test-ci.sh"
branches:
  only:
  - master
  - develop
  - "/^greenkeeper-.*$/"
sudo: false
cache:
  yarn: true
env:
  global:
  - CXX=g++-4.8
  - SAUCE_USERNAME=instantsearchjs
  - SAUCE_ACCESS_KEY=a3b366ec-c8d3-46af-8710-4d66992514ac
  - secure: DMNHPyjuZcxIly2N/mcqDEzeJ7gw5i6hOX+2dN8DW8CF6CFh2HIhA5Iznaerjst+gcHHRACWHT8BYstDExhaUAbegys1B/S3oDapLLT3H48a0VlpncAiyTvismv93tB7+WdoMAs+6zBMUo1z98At1ck6yUHsvASy7SNGVOI0UBRg5cu40eIrZTCKjhE6JXh2D2+HbFa7ODYy7aMl99A0Pk1SrFzehCVKd6+UhdY5Q+OKZNbPF3oDBifbAJeV54uYBPfgJJkj2CvWIIyGM33FRwrxZ/njwNgeCR1YMXNL0DEYQbyS3bBSkc/nSjE49vk8fY9m9n+CXjXsUsVWbGBBgsQTgOEQFjruNCiojXNuxTU3KLWjfDsdvT7KTnNj4lc1kfH10ESpVhhhfYLwmi9VaGyUlP825LYsdHidAWYVyLOcYufvUwXF+icpr2mEq9lG01pVZcX//GxsmQIcQ3/h3XEYfCBub7ZoiRYjoqL+AQWN+16OOW5DyC55DEI4FZClXtYP28u2z4VSpmPvE7X8kHO7fRtL5ZJyHcz9D3uVE8KlgBwtN4tOZ1tVJ8ssnaDeFJLtXpIAB/LwFdMbHNla+6gJ8aFvDiN2T97Y/Hk2/g4jO8pW1TAppnuON5pxsHy2bT46df1ad1OyINFsjtBYIQymlmVBAWalN242eDMyC+o=
  - secure: IReZG9KWjW8v+u/YmzGF8b+7zO0BC+cuvQGehxOXePnx01Ja+xrKeBv/RfO2E13vm3IoHByisPkeTWlnJA8h4/AwmvdOk33KkRBUVBABIsbvlN+uZ+jjz96K2VcD1ZjItSo7SrPEs+InRtsUfDBcr7burWUxL6tuhKcZT7wN+CT/QXBRN4Ai1z4DMFi5nK2vgOQ9u02IWjdzSXafDw4lhO+SEqNfMTDVXVqiSQ11Cyh7qsciiPkwxPhZWB3vg6YD0vU3GiYlgrC/Cr6hiCwiPi+9e+73MBwxsX8BYC0/2uM8vSMOocaePg1X9TOAP9sDCHW/MR8p+zfapV+7e7QBW2XaDy0j6m1rer1KwAhLSqCg4Gtp8Uc6qOS+W8NLnXzcUikLhkhp6/6TixsO2laKlr8sSwJ3o/qMyE7ViTyWQ/0qKZtYYFBxihT7bDzQI6C5nv+x8PZ5mFuhjaEb8PxYmgyXWznCnouqhYMHDn5geEzM3E3xjOhaIyqfNsqTX+nAkJGQR//GtZdyscKHsMD+7XVJ0AN+xRNtaEMCqVd5Tos3RT9ZSpD6eznltqL5RmASXcrKqLbuqh8ZkfpC549qvRDBFV4kOrZiiIb00H4ZcEH6WJjvRJ73EDb590HGIcsPqKlslXpRY1AhjK5AdiDnLZVrvayg+tGLFEL+8iC8q+A=
  - secure: c/zfrQ0nmOJYEx6zD+7KW0UgwQ1nlpAh1lubH+nSJwD3J3xdLi9Tm9XTy4iEiAXboxyaELgVPKaVG8kP+PzwjKfPx7a/sEYCKpkbsiTgQF4r0ldBHRX7eujbUVlYVACexBEgysDcQdg53TvuWuhctU9wk9kE9gjMFVzL61I+o7J+5wRhkhPW8A/t0eQnuqEuI9ZrYabZ6Nk1HSUidB7XGlTHeIHEQWtvCkq3Q25gOauhUeCik2ThCBlwDmvjIwkraQeKJHjd+AtmRczvfml9qh+XpT1fR9mP4nvaoiAzvjg6XsxbTlzx2D4wyI5FQNK+lpYJ/c3SfGpdIiuhE3yp8UAzkElTagFInOWLpD8hnKkbVJSUwFRW5qj/br6qyMUWKG23ItPPuRbbvR2x5zkhe2emRFtkvlQrRUZUgkDLWFh3o27t2cup2vrSGIeBUFN/TdwfQ67+x+am5h3mftzMWqCIcPdt/+ucq2xZ3Bhs+cYgjLZ6WkVkN+12Sq3q3TIICa7SDhhk3Uanz0+CuiyfK0fZd8ieUpzjNWQMxR1n8f+1EcfYNNNR71bS4sERy7HGovmemOKbYyBWx1/b2Mv/At2QlbVW1bTx/ry0xiETXf0aVETdLaVyLLBRvtj7AvqkGKP1QiwJCRa6lAhYZAeQ0Jl/9VzAII2RafiMTLUtLwA=
