title: instantsearch.js
description: instantsearch.js is a library of widgets designed to help you build high performance instant search experiences with Algolia
twitter_username: algolia
github_username: algolia
host: 0.0.0.0

incremental: true

# Navigation
navigation:
 - text: Documentation
   url: /documentation/
 - text: Examples
   url: /examples/
 - text: About
   url: /about/
 - text: React InstantSearch
   url: https://community.algolia.com/instantsearch.js/react/
# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: css

# Gems
gems:
  - algoliasearch-jekyll
  - jekyll-assets
  - jekyll-contentblocks

# search
algolia:
  application_id: latency
  index_name: instantsearch.js
  excluded_files:
    - index.haml
  record_css_selector: p,li,tr,h1,h2,h3,h4,h5,h6
  settings:
    highlightPostTag: </em>
    highlightPreTag: <em>
    ignorePlurals: true
    attributesToIndex:
      - title
      - text
      - category,subcategory,display_title
    attributesToHighlight:
      - category
      - subcategory
      - display_title
      - text
    customRanking:
      - desc(weight_tag_name)
      - asc(weight_order)
    ranking:
      - typo
      - words
      - proximity
      - attribute
      - custom
    attributesToSnippet:
      - text:20
